language: node_js
node_js:
  - 'lts/*'
#services:
#  - elasticsearch
before_install:
  #  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-amd64.deb
  #  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-amd64.deb.sha512
  #  - shasum -a 512 -c elasticsearch-7.3.2-amd64.deb.sha512
  #  - sudo dpkg -i --force-confnew elasticsearch-7.3.2-amd64.deb
  #  - sudo systemctl restart elasticsearch
  #  - sudo rm -rf /var/run/elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.3.1-amd64.deb
  - sudo service elasticsearch start
before_script:
  - sleep 30
  - rtn=$(curl "http://localhost:9200/?pretty")
  - echo $rtn
env:
  global:
    - NODE_ENV=test
    - SERVER_PROTOCOL=http
    - SERVER_HOSTNAME=localhost
    - SERVER_PORT=8888
    - ELASTICSEARCH_PROTOCOL=http
    - ELASTICSEARCH_HOSTNAME=localhost
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_INDEX=test
